-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:8889
-- Généré le : ven. 28 mars 2025 à 18:01
-- Version du serveur :  5.7.34
-- Version de PHP : 8.0.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANS1;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `SAE2.03`
--

CREATE DATABASE IF NOT EXISTS `SAE203` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `SAE203`;
-- --------------------------------------------------------

--
-- Structure de la table `Category`
--

CREATE TABLE `Category` (
  `id_category` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `Category`
--

INSERT INTO `Category` (`id_category`, `name`) VALUES
(1, "Action"),
(2, "Comédie"),
(3, "Drame"),
(4, "Science-fiction"),
(5, "Animation"),
(6, "Thriller"),
(7, "Horreur"),
(8, "Aventure"),
(9, "Fantaisie"),
(10, "Documentaire"),
(11, "Historique"),
(12, "Musical"),
(13, "Western");

-- --------------------------------------------------------

--
-- Structure de la table `Movie`
--

CREATE TABLE `Movie` (
  `id_movie` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(255) NOT NULL,
  `year` int(11) DEFAULT NULL,
  `length` int(11) DEFAULT NULL,
  `description` text,
  `director` varchar(255) DEFAULT NULL,
  `id_category` int(11),
  `image` varchar(255) DEFAULT NULL,
  `trailer` varchar(255) DEFAULT NULL,
  `min_age` int(11) DEFAULT 0,
  `featured` tinyint(1) DEFAULT 0,
  FOREIGN KEY (`id_category`) REFERENCES `Category`(`id_category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `Movie`
--

INSERT INTO `Movie` (`name`, `year`, `length`, `description`, `director`, `id_category`, `image`, `trailer`, `min_age`) VALUES
("Interstellar", 2014, 169, "Un groupe d’explorateurs voyage à travers un trou de ver pour sauver l’humanité.", "Christopher Nolan", 4, "interstellar.jpg", "https://www.youtube.com/embed/VaOijhK3CRU?si=76Ke4uw4LYjuLuQ6", 12),
("La Liste de Schindler", 1993, 195, "Un industriel allemand sauve des milliers de Juifs pendant l’Holocauste.", "Steven Spielberg", 3, "schindler.webp", "https://www.youtube.com/embed/ONWtyxzl-GE?si=xC3ASGGPy5Ib-aPn", 16),
("Your Name", 2016, 107, "Deux adolescents échangent leurs corps de manière mystérieuse.", "Makoto Shinkai", 5, "your_name.jpg", "https://www.youtube.com/embed/AROOK45LXXg?si=aUQyGk2VMCb_ToUL", 10),
("Le Bon, la Brute et le Truand", 1966, 161, "Trois hommes se lancent à la recherche d’un trésor caché.", "Sergio Leone", 13, "bon_brute_truand.jpg", "https://www.youtube.com/embed/WA1hCZFOPqs?si=TwNZAoM4oj4KpGja", 12);
("À la croisée des mondes : La Boussole d’or",	2007,	113,	"Dans un monde parallèle où l’âme humaine prend la forme d’un animal familier, une courageuse orpheline nommée Lyra voyage vers le Grand Nord pour sauver ses amis kidnappés et percer le mystère d’une particule cosmique appelée la Poussière.",	"Chris Weitz",	9,	"a_la_croisee_des_mondes-la_boussole_dor.jpg", "https://www.youtube.com/embed/LHYoOGfBObU?si=f0g7gMp_RjwBCYA5",	10),
("Apex",	2026,	135,	"Sasha pratique l’escalade de haut niveau. Frappée par un deuil, elle tente de se changer les idées en grimpant sur des falaises en forêt. Elle est alors prise en chasse par un braconnier inconnu. Tout en luttant contre les éléments naturels, elle va devoir affronter cet ennemi mystérieux. Elle ne pourra pas compter sur l’aide de son partenaire.",	"Baltasar Kormákur",	1,	"apex.jpg",	"https://www.youtube.com/watch?v=ELJ_orzMy1M",	16),
("Arthur et les Minimoys",	2006,	94,	"Un garçon découvre un monde miniature et part à l’8 pour sauver sa maison.",	"Luc Besson",	5,	"arthur_et_les_minimoys.jpg",	"https://www.youtube.com/watch?v=xMP0WpiFHCE",	0),
("Astérix et Obélix : Mission Cléopâtre",	2002,	107,	"Cléopâtre, piquée au vif par Jules César qui dénigre la grandeur de son peuple, lui lance un défi : construire en trois mois un palais somptueux qui prouvera la supériorité de la civilisation égyptienne. Elle confie cette mission impossible à l’architecte Numérobis, menacé d’être jeté aux crocodiles en cas d’échec. Conscient de l’ampleur du chantier, Numérobis part chercher de l’aide en Gaule auprès du druide Panoramix, accompagné d’Astérix et Obélix. Ensemble, ils se rendent en Égypte pour accélérer la construction grâce à la potion magique. Mais Amonbofis, architecte rival jaloux, multiplie les sabotages, parfois avec l’appui des Romains. Entre complots, grèves, poursuites, pièges et affrontements, les Gaulois doivent déjouer tous les obstacles pour permettre à Numérobis de terminer le palais dans les temps. Leur réussite forcera César à reconnaître publiquement la grandeur du peuple égyptien.",	"Alain Chabat",	2,	"asterix_et_obelix_mission_cleopatre.jpg",	"https://www.youtube.com/embed/7Nd1ZCwB5PI?si=XBkpY0JI_AbEF2n7",	0),
("Bee Movie",	2007,	91,	"Une abeille intente un procès contre les humains pour exploitation du miel.",	"Simon J. Smith, Steve Hickner",	5,	"bee_movie.jpg",	"https://www.youtube.com/watch?v=jJw4UyV21qU",	0),
("Blade Runner 2049",	2017,	163,	"En 2049, la société est fragilisée par les nombreuses tensions entre les humains et leurs esclaves créés par bio-ingénierie. L’officier K est un Blade Runner: il fait partie d’une force d’intervention d’élite chargée de trouver et d’éliminer ceux qui n’obéissent pas aux ordres des humains.",	"Denis Villeneuve",	4, "blade_runner_2049.jpg",	"https://youtu.be/O4C5cwSbXZ8?si=pE1F4vJTC72quGIw",	0),
("Bullet Train", 2022,	127,	"Coccinelle est un assassin malchanceux et particulièrement déterminé à accomplir sa nouvelle mission paisiblement après que trop d’entre elles aient déraillé. Mais le destin en a décidé autrement et l’embarque dans le train le plus rapide au monde aux côtés d’adversaires redoutables qui ont tous un point commun, mais dont les intérêts divergent radicalement... Il doit alors tenter par tous les moyens de descendre du train.", 	"David Leitch",	2,	"bullet_train.jpg",	"https://www.youtube.com/watch?v=N9W-5g6Zp2s",	12),
("Citizenfour",	2014,	114,	'En 2013, Laura Poitras reçoit des e-mails cryptés d’un mystérieux "CITIZENFOUR" qui prétend détenir des preuves de programmes de surveillance illégaux menés par la NSA. Elle se rend à Hong Kong avec les journalistes Glenn Greenwald et Ewen MacAskill pour rencontrer l’informateur, qui s’avère être Edward Snowden. Le film capture en temps réel les révélations qui ont secoué le monde et les conséquences immédiates pour Snowden.',	"Laura Poitras",	10,	"citizenfour.jpg",	"https://youtu.be/_VD7nnONpJE?si=ERcN2i3Bl5PigHHB",	0),
("Conjuring 1 : les dossiers Warren",	2013,	112,	"Avant Amityville, il y avait Harrisville… Conjuring : Les dossiers Warren, raconte l’histoire horrible, mais vraie, d’Ed et Lorraine Warren, enquêteurs paranormaux réputés dans le monde entier, venus en aide à une famille terrorisée par une présence inquiétante dans leur ferme isolée… Contraints d’affronter une créature démoniaque d’une force redoutable, les Warren se retrouvent face à l’affaire la plus terrifiante de leur carrière…",	"James Wan",	7,	"conjuring1.jpg",	"https://www.youtube.com/watch?v=Mkf9rGLXeuE",	12),
("Conjuring 2 : le cas Enfield", 	2016,	134,	"Les époux Warren se rendent dans la banlieue de Londres à la demande d’un prêtre afin de s’occuper du cas de Janet, une petite fille de 11 ans possédée par un démon. Peggy, la mère de Janet, ainsi que les soeurs de la fillette, sont terrifiées. Ed et Lorraine se rendent rapidement compte que l’affaire est sérieuse, et surtout, qu’ils ne sont pas là par hasard. L’entité qui a pris possession de Janet les connaît, et les hait assez pour vouloir les éliminer. Le second épisode d’une franchise d’7 dont la réussite ne repose pas uniquement sur sa capacité à faire sursauter le spectateur. Les décors, la musique, les effets sonores : tout concourt à placer le public dans une ambiance sinistre à souhait.", 	"James Wan",	7,	"conjuring2.jpg",	"https://www.youtube.com/watch?v=Y3kNhv0Nm_g",	12),
("Conjuring 3 : Sous l’emprise du Diable",	2021,	112,	"Conjuring 3 : sous l’emprise du diable retrace une affaire terrifiante de meurtre et de présence maléfique mystérieuse qui a même ébranlé les enquêteurs paranormaux Ed et Lorraine Warren, pourtant très aguerris. Dans cette affaire issue de leurs dossiers secrets – l’une des plus spectaculaires – , Ed et Lorrain commencent par se battre pour protéger l’âme d’un petit garçon, puis basculent dans un monde radicalement inconnu. Ce sera la première fois dans l’histoire des États-Unis qu’un homme soupçonné de meurtre plaide la possession démoniaque comme ligne de défense.",	"Michael Chaves",	7,	"conjuring3.jpg",	"https://www.youtube.com/watch?v=YjN7cRbaZzE",	12),
("Conjuring 4 : L’Heure du jugement", 2025,	135,	"Alors qu’ils espéraient une nouvelle vie, Ed et Lorraine Warren se voient impliqués dans une dernière enquête… qu’ils n’auraient jamais dû accepter. Dans la maison de la famille Smurl, un mal ancien les attend. Un ennemi qu’ils croyaient à jamais enfoui... Découvrez comment les Warren ont affronté le cas le plus maléfique de leur carrière, inspiré de faits réels qui ont terrorisé l’Amérique.", 	"Michael Chaves", 	7,	"conjuring4.jpg",	"https://www.youtube.com/watch?v=pANEpIq6UZI",	12),
("Coraline",	2009,	100,	'Coraline Jones est une fillette intrépide qui découvre une porte secrète dans sa nouvelle maison. Elle débouche sur un monde parallèle qui ressemble étrangement au sien, mais en mieux. Cependant, cette 8 fantastique devient dangereuse quand sa "Mère" tente de la garder prisonnière à jamais.',	"Henry Selick", 9,	"coraline.jpg",	"https://www.youtube.com/watch?v=8CC7-5sYJv8",	0),
("Danse avec les loups",	1990,	236,	'Le jeune lieutenant John Dunbar est envoyé à un poste de reconnaissance dans les immenses plaines du Dakota pendant la guerre de Sécession. Il rencontre au cours de l’une de ses missions de reconnaissance le peuple sioux. Le lieutenant se lie d’amitié avec la population indienne. Il arrive même à intégrer la tribu, au point d’être surnommé "Danse avec les loups", et de s’éprendre d’une des leurs, une blanche baptisée "Dressée avec le poing".', 	"Kevin Costner",	13, "danse_avec_les_loups.jpg",	"https://www.youtube.com/watch?v=dbYwm6IBq54",	0),
("Demon Slayer : La Forteresse Infinie Film 1", 2025,	155,	"Tanjirô Kamado a rejoint une organisation dédiée à la chasse aux démons, les pourfendeurs de démons, après que sa jeune sœur Nezuko ait été transformée en démon. Devenant de plus en plus fort et proche des autres membres de l’armée, Tanjirô affronte de nombreux démons en compagnie de ses camarades, Zen’itsu Agatsuma et Inosuke Hashibira. Ses 8s l’ont amené à se battre aux côtés des combattants les plus hauts placés de l’armée des pourfendeurs de démons, les piliers, tels que le pilier de la flamme, Kyôjurô Rengoku, dans le train de l’infini, le pilier du son, Tengen Uzui, dans le quartier des plaisirs, ainsi que le pilier de la brume, Muichirô Tokitô, et le pilier de l’amour, Mitsuri Kanroji, dans le village des forgerons. Alors que l’armée des pourfendeurs de démons et les piliers s’exerçaient lors d’une session d’entraînement en prévision du futur affrontement contre les démons, Muzan Kibutsuji fait son apparition au manoir Ubuyashiki. Le responsable de l’armée étant en danger, Tanjirô et les piliers se ruent vers le quartier général, mais tombent dans le piège tendu par Muzan Kibutsuji et se retrouvent coincés dans les profondeurs d’un espace mystérieux. Tanjirô et le reste de l’armée des pourfendeurs de démons sont téléportés dans le bastion des démons : la Forteresse infinie. C’est là que s’embrasera l’ultime combat entre l’armée des pourfendeurs de démons et les forces démoniaques.", 	"Haruo Sotozaki", 	5,	"demon_slayer-la_forteresse_infinie.jpg",	"https://www.youtube.com/watch?v=KiWTr1AQ33M",	12),
("Django Unchained",	2012,	165,	"Dans le sud des États-Unis, deux ans avant la guerre de Sécession, le chasseur de primes d’origine allemande, le Dr King Schultz, fait l’acquisition de Django, un esclave qui peut l’aider à traquer les frères Brittle. En échange, Schultz promet de libérer Django et de l’aider à retrouver sa femme, Broomhilda, retenue par le redoutable propriétaire d’une plantation, Calvin Candie.",	"Quentin Tarantino",	1, "django_unchained.jpg",	"https://www.youtube.com/watch?v=K2XjgsfzDrU",	16),
("Dragons",	2010,	98,	"Un jeune Viking se lie d’amitié avec un dragon, changeant la vision de son peuple.",	"Chris Sanders, Dean DeBlois",	9,	"dragons1.jpg",	"https://www.youtube.com/watch?v=d0grS8PYUn0",	0),
("Dragons", 2025,	125,	"Sur l’île escarpée de Beurk, où depuis des générations Vikings et dragons s’affrontent sans merci, Harold fait figure d’exception. Effacé, écrasé par la stature de son père, le chef de la tribu, Stoïk, ce jeune rêveur défie des siècles de tradition en se liant d’amitié avec un dragon nommé Krokmou. Leur lien improbable va révéler la vraie nature des dragons et remettre en question les fondements mêmes de la société viking. Flanqué de la farouche Astrid et de Gueulfor, le sympathique forgeron du village, Harold va devoir s’imposer dans un monde déchiré par la peur et l’incompréhension. Alors qu’une dangereuse créature réémerge des brumes du passé, menaçant à la fois les Vikings et les dragons, l’amitié d’Harold et Krokmou pourrait bien être la clef d’un nouvel avenir. Ensemble, ils vont devoir se frayer un chemin fragile vers la paix, en dépassant les limites de leurs deux mondes pour mieux redéfinir les notions de chef et de héros.",	"Dean DeBlois",	9,	"dragons_live1.jpg",	"https://www.youtube.com/watch?v=seY55AKGmxQ",	0),
("Dragons 2",	2014,	102,	"Tandis qu’Astrid, Rustik et le reste de la bande se défient durant des courses sportives de dragons devenues populaires sur l’île, notre duo désormais inséparable parcourt les cieux, à la découverte de territoires inconnus et de nouveaux mondes. Au cours de l’une de leurs 8s, ils découvrent une grotte secrète qui abrite des centaines de dragons sauvages, dont le mystérieux Dragon Rider. Les deux amis se retrouvent alors au centre d’une lutte visant à maintenir la paix. Harold et Krokmou vont se battre pour défendre leurs valeurs et préserver le destin des hommes et des dragons.", "Dean DeBlois",	9,	"dragons2.jpg",	"https://www.youtube.com/watch?v=lm4ApfTrLKs",	0),
("Dragons 3 : Le Monde Caché",	2019,	104,	"Harold est maintenant le chef de Berk au côté d’Astrid et Krokmou, en tant que dragon, est devenu le leader de son espèce. Ils réalisent enfin leurs rêves de vivre en paix entre vikings et dragons. Mais lorsque l’apparition soudaine d’une Furie Eclair coïncide avec la plus grande menace que le village n’ait jamais connue, Harold et Krokmou sont forcés de quitter leur village pour un voyage dans un monde caché dont ils n’auraient jamais soupçonnés l’existence. Alors que leurs véritables destins se révèlent, dragons et vikings vont se battre ensemble jusqu’au bout du monde pour protéger tout ce qu’ils chérissent.",	"Dean DeBlois",	9,	"dragons3.jpg",	"https://www.youtube.com/watch?v=lNYDeG4Qd4k",	0),
("Fantastic Mr. Fox",	2009,	87,	"Un renard rusé vole les fermiers voisins, mettant sa famille en danger.",	"Wes Anderson",	5,	"fantastic_mr_fox.jpg",	"https://www.youtube.com/watch?v=_AyJLSef4y4",	0),
("Five Nights At Freddy’s",	2023,	109,	"Mike, jeune homme perturbé, s’occupe de sa sœur Abby, âgée de 10 ans. Il est toujours hanté par la disparition, jamais élucidée, de son petit frère, survenue il y a une dizaine d’années. Récemment licencié, il a absolument besoin de retrouver un emploi pour ne pas perdre la garde d’Abby. Il accepte donc un poste de gardien de nuit, dans un restaurant désaffecté : Freddy Fazbear’s Pizzeria. Mais Mike ne tarde pas à comprendre que les apparences y sont terriblement trompeuses. Avec l’aide de Vanessa Shelly, agent de police, il est confronté, la nuit, à des phénomènes surnaturels inexplicables et bascule dans un univers cauchemardesque...", "Emma Tammi", 	7,	"fnaf.jpg",	"https://www.youtube.com/watch?v=iUgc6N37QmU",	12),
("Five Nights at Freddy's 2", 2025,	104,	"Un an après l'enfer surnaturel de la pizzéria de Freddy Fazbear, un nouveau chapitre de terreur débute lorsqu'Abby, la sœur de l'ex-gardien de sécurité Mike, part à la recherche de ses amis animatroniques : Freddy, Bonnie, Chica et Foxy. Alors que les événements terrifiants s'enchaînent, des secrets sur les origines de Freddy surgissent et déclenchent une 7 disparue depuis des décennies.", "Emma Tammi",	7, "fnaf2.jpg",	"https://www.youtube.com/watch?v=3SzKVYbCOks",	12),
("Forrest Gump",	1994,	142,	"Quelques décennies d'histoire américaine, des années 1940 à la fin du XXème siècle, à travers le regard et l'étrange odyssée d'un homme simple et pur, Forrest Gump.", 	"Robert Zemeckis", 	3,	"forrest_gump.jpg",	"https://www.youtube.com/watch?v=q2AP7dAeVhw",	0),
("Gladiator",	2000,	155,	"Le général romain Maximus est le plus fidèle soutien de l'empereur Marc Aurèle, qu'il a conduit de victoire en victoire avec une bravoure et un dévouement exemplaires. Jaloux du prestige de Maximus, et plus encore de l’amour que lui voue l’empereur, le fils de MarcAurèle, Commode, s’arroge brutalement le pouvoir, puis ordonne l’arrestation du général et son exécution. Maximus échappe à ses assassins mais ne peut empêcher le massacre de sa famille. Capturé par un marchand d’esclaves, il devient gladiateur et prépare sa vengeance.", "Ridley Scott",	11, "gladiator1.jpg",	"https://www.youtube.com/watch?v=ChcgxBAzrks",	0),
("Gladiator II",	2024,	148,	"Des années après avoir assisté à la mort du héros vénéré Maximus aux mains de son oncle, Lucius est forcé d’entrer dans le Colisée lorsque son pays est conquis par les empereurs tyranniques qui gouvernent désormais Rome d’une main de fer. La rage au cœur et l’avenir de l’Empire en jeu, Lucius doit se tourner vers son passé pour trouver la force et l’honneur de rendre la gloire de Rome à son peuple.", 	"Ridley Scott", 11,	"gladiator2.jpg",	"https://www.youtube.com/watch?v=APv2lidaDmo",	12),
("Hannibal : Le Cauchemar de Rome", 	2006,	89,	'"Je jure qu’aussi longtemps que je vivrai, je demeurerai un ennemi de Rome." Depuis l’enfance, sa vie fut consacrée à la destruction du plus grand empire que le monde ait connu. Hannibal, le plus grand ennemi de Rome raconte l’extraordinaire épopée du seul homme qui ait fait plier la puissance de Rome.', 	"Edward Bazalgette",	10,	"hannibal_le_cauchemar_de_rome.jpg",	"https://www.youtube.com/watch?v=POIZn7Hk_Mg&t=2s",	10),
("I Robot", 2004,	115,	"Un policier enquête sur un robot impliqué dans un meurtre malgré les lois de la robotique.",	"Alex Proyas",	4,	"i_robot.jpg",	"https://www.youtube.com/watch?v=PjECS38ZGWE",	10),
("Il était une fois dans l’Ouest",	1968,	165,	"Alors qu’il prépare une fête pour sa femme, Bet McBain est tué avec ses trois enfants. Jill McBain hérite des terres de son mari, convoitées par Morton, le commanditaire du crime, car elles prennent de la valeur avec l’arrivée imminente du chemin de fer. Cependant, les soupçons se portent sur un aventurier, Cheyenne...",	"Sergio Leone",	13, "il_etait_une_fois_dans_louest.jpg",	"https://www.youtube.com/watch?v=Gmnxd5QD2uo",	0),
("Inception", 	2010,	158,	"Dom Cobb est un voleur expérimenté – le meilleur qui soit dans l’art périlleux de l’extr1 : sa spécialité consiste à s’approprier les secrets les plus précieux d’un individu, enfouis au plus profond de son subconscient, pendant qu’il rêve et que son esprit est particulièrement vulnérable. Très recherché pour ses talents dans l’univers trouble de l’espionnage industriel, Cobb est aussi devenu un fugitif traqué dans le monde entier qui a perdu tout ce qui lui est cher. Mais une ultime mission pourrait lui permettre de retrouver sa vie d’avant – à condition qu’il puisse accomplir l’impossible : l’inception. Au lieu de subtiliser un rêve, Cobb et son équipe doivent faire l’inverse : implanter une idée dans l’esprit d’un individu. S’ils y parviennent, il pourrait s’agir du crime parfait. Et pourtant, aussi méthodiques et doués soient-ils, rien n’aurait pu préparer Cobb et ses partenaires à un ennemi redoutable qui semble avoir systématiquement un coup d’avance sur eux. Un ennemi dont seul Cobb aurait pu soupçonner l’existence.", "Christopher Nolan",	6,	"inception.jpg",	"https://www.youtube.com/watch?v=HcoZbHBDHQA",	0),
("Independence Day",	1996,	145,	"L’humanité affronte une invasion extraterrestre destructrice.",	"Roland Emmerich",	4,	"independance_day.jpg",	"https://www.youtube.com/watch?v=lYaVIrVB9x8",	10),
("Inglourious Basterds",	2009,	153,	'Dans la France occupée, Shosanna Dreyfus assiste à l’exécution de sa famille par le colonel nazi Hans Landa. Elle parvient à s’échapper et s’enfuit à Paris où elle devient propriétaire d’un cinéma. Ailleurs en Europe, le lieutenant Aldo Raine forme un groupe de soldats juifs américains pour mener des 1s punitives particulièrement sanglantes contre les nazis. "Les Bâtards", comme l’ennemi les surnomme, se joignent à l’actrice allemande et agent secret Bridget von Hammersmark pour tenter d’éliminer les hauts dignitaires du Troisième Reich lors d’une première de film dans le cinéma de Shosanna. Leurs destins vont se croiser lors d’une soirée qui pourrait bien changer le cours de l’Histoire.',	"Quentin Tarantino",	1,	"inglourious_basterds.webp",	"https://www.youtube.com/watch?v=BiPUoLI9eGM",	16),
("James Bond Skyfall",	2012,	143,	"Lorsqu’une mission tourne mal à Istanbul, James Bond est porté disparu et présumé mort. Peu après, le MI6 subit une attaque informatique qui vise directement M, révélant qu’un ennemi intime connaît ses secrets et cherche à la détruire. Bond réapparaît et reprend du service malgré une condition physique affaiblie, déterminé à identifier l’auteur de ces attaques.  Son enquête le mène jusqu’à Raoul Silva, ancien agent du MI6 devenu cyber‑terroriste, animé par une vengeance personnelle contre M. Pour protéger son service et affronter ce passé qui ressurgit, Bond doit repousser ses limites et revenir sur les traces de son enfance, jusqu’au manoir familial de Skyfall, où se joue l’affrontement final.", "Sam Mendes", 1,	"james_bond_skyfall.jpg",	"https://www.youtube.com/watch?v=WKzm6AZFbdc",	12),
("John Wick : Chapitre 1",	2014,	101,	"Depuis la mort de sa femme bien-aimée, John Wick passe ses journées à retaper sa Ford Mustang de 1969, avec pour seule compagnie sa chienne Daisy. Il mène une vie sans histoire, jusqu’à ce qu’un malfrat sadique nommé Iosef Tarasof remarque sa voiture. John refuse de la lui vendre. Iosef n’acceptant pas qu’on lui résiste, s’introduit chez John avec deux complices pour voler la Mustang, et tuer sauvagement Daisy… John remonte la piste de Iosef jusqu’à New York. Un ancien contact, Aurelio, lui apprend que le malfrat est le fils unique d’un grand patron de la pègre, Viggo Tarasof. La rumeur se répand rapidement dans le milieu : le légendaire tueur cherche Iosef. Viggo met à prix la tête de John : quiconque l’abattra touchera une énorme récompense. John a désormais tous les assassins de New York aux trousses.",	"Chad Stahelski",	1,	"john_wick1.jpg",	"https://www.youtube.com/watch?v=pWK5crMuhHY",	12),
("John Wick : Chapitre 2",	2017,	122,	"John Wick est forcé de sortir de sa retraite volontaire par un de ses ex-associés qui cherche à prendre le contrôle d’une mystérieuse confrérie de tueurs internationaux. Parce qu’il est lié à cet homme par un serment, John se rend à Rome, où il va devoir affronter certains des tueurs les plus dangereux du monde.", 	"Chad Stahelski",	1,	"john_wick2.jpg",	"https://www.youtube.com/watch?v=_QtgfA8PjAw",	12),
("John Wick : Chapitre 3",	2019,	130,	"John Wick est en fuite après avoir enfreint la règle suprême du Continental : tuer un homme dans l’enceinte de l’hôtel. Déclaré excommunicado, il perd tous ses droits, son accès aux services du monde criminel et voit sa tête mise à prix pour 14 millions de dollars.  Traqué par des assassins du monde entier, il tente de survivre tout en cherchant un moyen d’effacer sa condamnation. Son parcours le mène de New York au Maroc, où il affronte de nouveaux ennemis et sollicite d’anciens alliés.",	"Chad Stahelski",	1,	"john_wick3.webp",	"https://www.youtube.com/watch?v=Cs4wKxXjkc8",	12),
("John Wick : Chapitre 4",	2023,	169,	"John Wick poursuit sa lutte contre la Grande Table, l’organisation toute‑puissante qui régit le monde criminel. Alors qu’une nouvelle figure d’autorité, le Marquis de Gramont, reçoit les pleins pouvoirs pour éliminer Wick, ce dernier doit affronter des assassins toujours plus nombreux et déterminés. Pour retrouver sa liberté, John se tourne vers d’anciens alliés, voyageant entre New York, Osaka, Berlin et Paris. Chaque étape le rapproche d’un duel final qui pourrait enfin briser le cycle de violence… ou l’achever définitivement.", "Chad Stahelski",	1,	"john_wick4.webp",	"https://www.youtube.com/watch?v=6itn_8L6-Z8",	12),
("Joker",	2019,	122,	"L’histoire sombre d’un homme marginal qui devient le célèbre criminel Joker.",	"Todd Phillips",	3,	"joker.jpg",	"https://www.youtube.com/watch?v=HL3EuCbcOAo",	16),
("Jules César",	2007,	135,	"Opposé au dictateur Sulla, chef du parti sénatorial, le jeune Jules César ne recule devant rien et va jusqu'à faire exécuter ses ennemis. Compromis par son mariage, il fuit Rome pour y revenir lors de la chute du dictateur. il va ensuite exposé ses convictions et valeurs pour devenir, l'un des plus grand empereur de l'histoire...", 	"Uli Edel",	10,	"jules_cesar.jpg",	"https://www.youtube.com/watch?v=FsL1LpIbqJE",	10),
("Kpop Demon Hunter",	2025,	95,	"Les membres d'un groupe de K-Pop célèbre doivent concilier leur vie sous les feux de la rampe et leur identité secrète de chasseuses de démons, le tout baignant dans un décor coloré de mode, de cuisine, de style et du mouvement musical le plus populaire de la génération actuelle.", "Maggie Kang, Chris Appelhans", 	5,	"kpop_demon_hunter.jpg",	"https://www.youtube.com/watch?v=Zav4B-FdjTs",	0),
("Kung fu panda", 	2008,	132,	"Un panda maladroit devient un maître du kung-fu pour sauver la vallée de la paix.",	"Mark Osborne",	5,	"kungfu_panda1.jpg",	"https://www.youtube.com/watch?v=yt9r0Q5za38",	0),
("La Planète au Trésors  : Un nouvel univers",	2002,	95,	'Jim Hawkins, un garçon de quinze ans, vit paisiblement avec sa mère dans une ville portuaire. Un jour, il tombe sur un homme gravement blessé, mais il ne peut le sauver d’une mort certaine. L’homme, du nom de Billy Bones, lui remet un orbe précieux qui contient une carte. Celle-ci mène à un fabuleux trésor de pirates, le légendaire "butin des mille mondes". Le docteur Doppler organise rapidement une expédition à bord du RLS Legacy, un magnifique galion de l’espace. Jim entreprend ce fantastique voyage comme mousse. Grâce aux conseils bienveillants de son ami John Silver, le charismatique cyborg cuisinier du navire, le jeune garçon devient un talentueux navigateur. Il affronte, avec les autres membres de l’équipage, les supernovas, les trous noirs et les terribles tempêtes du cosmos. Mais il découvre bientôt que son vieil ami Silver est en fait un pirate qui complote une mutinerie.',	"Ron Clements, John Musker", 	5,	"la_planete_au_tresors.jpg",	"https://www.youtube.com/watch?v=2jAbiaE4lww",	0),
("Le Château ambulant", 2004,	119,	"La jeune Sophie, 18 ans, travaille inlassablement dans la chapellerie autrefois tenue par son père, malheureusement décédé. Résignée à son sort, c’est lors de l’une de ses rares sorties en ville qu’elle fait la connaissance du beau Hauru, un magicien. Mais la sorcière des Landes, jalouse de cette rencontre, jette un sort à Sophie, la transformant en vieille dame. Accablée par sa nouvelle apparence, Sophie s’enfuit dans les montagnes et tombe sur la demeure de Hauru : son Château Ambulant. Et si tout ceci n’était que le commencement d’une merveilleuse histoire ?", 	"Hayao Miyazaki", 5,	"le_chateau_ambulant.jpg",	"https://www.youtube.com/watch?v=hhdopPrI68Q",	0),
("Le Comte de Monte-Cristo", 	2024,	178,	"Victime d’un complot, le jeune Edmond Dantès est arrêté le jour de son mariage pour un crime qu’il n’a pas commis. Après quatorze ans de détention au château d’If, il parvient à s’évader. Devenu immensément riche, il revient sous l’identité du comte de Monte-Cristo pour se venger des trois hommes qui l’ont trahi.", "Alexandre de La Patellière, Matthieu Delaporte",	8,	"le_comte_de_montecristo.jpg",	"https://www.youtube.com/watch?v=u0YnbsyvGS0",	0),
("Le Labyrinthe",	2014,	113,	"Un groupe d’adolescents tente de s’échapper d’un labyrinthe géant.",	"Wes Ball",	4,	"le_labyrinthe.jpg",	"https://www.youtube.com/watch?v=LyPiCH_4Al4",	12),
("Le Magicien d’Oz", 1939,	102,	"Dorothy, jeune orpheline, vit chez son oncle et sa tante. Tout irait pour le mieux si l’institutrice ne détestait pas son chien. C’est alors que Dorothy fait un rêve où elle se trouve transportée au royaume magique des Munchkins à la recherche de son chien. Les Munchkins sont des nains protégés par la bonne fée du Nord mais menacés par la méchante fée de l’Ouest. Pour retrouver son chien, Dorothy doit s’emparer des chaussures rouges de la mauvaise fée et aller voir le magicien d’Oz dans son palais d’Emeraude.", "Victor Fleming, , King Vidor, George Cukor",	12, "le_magicien_doz.jpg",	"https://www.youtube.com/watch?v=2lc9J_UjdHk",	0),
("Le Monde de Narnia :  Le Monde de Narnia : Le Prince Caspian", 	2008,	150,	"Un an après les incroyables événements du Monde de Narnia - Chapitre 1, les nouveaux rois et reines de Narnia sont de retour dans ce royaume magique. Mais à Narnia, plus de 1000 années se sont écoulées. L’Age d’Or du royaume est depuis longtemps révolu, et ce n’est plus maintenant qu’une légende. Les animaux parlants et les créatures mythiques ont disparu, ils ne sont plus évoqués que comme les héros d’un folklore que l’on perpétue chez les Telmarins, une race d’humains dirigée par le maléfique roi Miraz, qui règne sans pitié sur Narnia. Même si l’on se souvient encore du nom d’Aslan dans la forêt, le puissant lion n’est pas revenu depuis un millier d’années. Les quatre enfants ont été rappelés à Narnia par le Prince Caspian, le jeune héritier du trône des Telmarins. Sa vie est en danger : son oncle Miraz cherche à l’éliminer afin que son propre fils nouveau-né puisse monter sur le trône à sa place. Avec l’aide du gentil Nain rouge, d’une courageuse souris parlante nommée Ripitchip, et du Nain noir aigri et revêche Nikabrik, les Narniens, menés par les puissants rois Peter et Caspian, s’engagent dans une formidable quête à la recherche d’Aslan, afin de sauver Narnia de la tyrannie de Miraz et de rendre sa gloire et sa magie au royaume....", 	"Andrew Adamson", 	9,	"narnia2.jpg",	"https://www.youtube.com/watch?v=-lvcgBLG1Po",	0),
("Le Monde de Narnia : Le Lion, la Sorcière blanche et l'Armoire magique",	2005,	143,	"Le Monde de Narnia : chapitre 1 conte la lutte entre le bien et le mal qui oppose le magnifique lion Aslan aux forces des ténèbres dans le monde magique de Narnia. Grâce à ses sombres pouvoirs, la Sorcière Blanche a plongé Narnia dans un hiver qui dure depuis un siècle, mais une prédiction révèle que quatre enfants aideront Aslan à rompre la malédiction. Lorsque Lucy, Susan, Edmund et Peter Pevensie, quatre frères et soeurs, découvrent ce monde enchanté en y pénétrant à travers une armoire, tout est en place pour une bataille de proportions épiques...", 	"Andrew Adamson",	9,	"narnia1.jpg",	"https://www.youtube.com/watch?v=ztFix1KQmSI",	0),
("Le Monde de Narnia : Le Monde de Narnia : L'Odyssée du Passeur d'Aurore",	2010,	112,	"Happés à l’intérieur d’un intriguant tableau, Edmund et Lucy Pevensie, ainsi que leur détestable cousin Eustache, se retrouvent subitement projetés dans le royaume de Narnia, à bord d’un navire majestueux : le Passeur d’Aurore. Rejoignant Caspian, devenu roi, et l’intrépide souris guerrière Ripitchip, ils embarquent pour une périlleuse mission dont dépend le sort même de Narnia. A la recherche de sept seigneurs disparus, nos voyageurs entament un envoûtant périple vers les îles mystérieuses de l’Est, où ils ne manqueront pas de rencontrer tant de créatures magiques que de merveilles inimaginables. Mais ils devront surtout vaincre leurs peurs les plus profondes en affrontant de sinistres ennemis, tout en résistant à de terribles tentations auxquelles ils seront confrontés. Il est temps pour eux de faire preuve d’un courage légendaire au cours d’une odyssée qui les transformera à jamais et les emportera au bout du monde, où le grand Lion Aslan les attend.", 	"Michael Apted", 	9,	"narnia3.jpg",	"https://www.youtube.com/watch?v=8wat1vJDHtY",	0),
("Le Monde de Nemo",	2003,	100,	"Un poisson clown traverse l’océan pour retrouver son fils capturé.",	"Andrew Stanton",	5,	"le_monde_de_nemo.jpg",	"https://www.youtube.com/watch?v=TKi8VJmBuLs",	0),
("Le Parrain", 	1972,	175,	'En 1945, à New York, les Corleone sont une des cinq familles de la mafia. Don Vito Corleone marie sa fille à un bookmaker. Sollozzo, "parrain" de la famille Tattaglia, propose à Don Vito une association dans le trafic de drogue...', "Francis Ford Coppola",	6,	"le_parrain.jpg",	"https://www.youtube.com/watch?v=bmtuIhesQWA",	12),
("Le Voyage de Chihiro",	2001,	125,	"Une fillette de dix ans se retrouve piégée dans un monde peuplé d’esprits et doit trouver un moyen de libérer ses parents transformés en cochons.",	"Hayao Miyazaki",	5,	"le_voyage_de_chihiro.jpg",	"https://www.youtube.com/embed/ByXuk9QqQkk?si=rupK5RJwRKaTWCLi",	0),
("Les Trolls 1",	2016,	92,	"Connus pour leur crête de cheveux fluos et magiques, les Trolls sont des créatures délirantes et joyeuses et surtout les rois de la pop. Mais leur monde d’arcs-en-ciel et de cupcakes est changé à jamais lorsque leur leader Poppy, accompagnée de Branche et tous ses amis, doit se lancer dans une mission de sauvetage qui l’entraînera loin de ce petit paradis.", "Mike Mitchell, Walt Dohrn", 12,	"les_trolls1.jpg",	"https://www.youtube.com/watch?v=AgTAQqlEscM",	0),
("Les Trolls 2 : Tournée mondiale", 	2020,	91,	"Reine Barb, membre de la royauté hard-rock, aidée de son père Roi Thrash, veut détruire tous les autres genres de musique pour laisser le rock régner en maître. Le destin du monde en jeu, Poppy et Branch, accompagnés de leurs amis – Biggie, Chenille, Satin, Cooper et Guy Diamond – partent visiter tous les autres territoires pour unifier les Trolls contre Barb, qui cherche à tous les reléguer au second-plan.", 	"Walt Dohrn, David P. Smith", 12,	"les_trolls2.jpg",	"https://www.youtube.com/watch?v=syTnm7JWz2U",	0),
("Les Trolls 3 : Nouvelle Tournée",	2023,	92,	"Après deux films à se tourner autour pour finalement tomber dans les bras l’un de l’autre, Poppy et Branch sont officiellement en couple ! Alors qu’ils n’ont plus de secrets l’un pour l’autre, Poppy fait une découverte incroyable relative au passé de Branch. À l’époque, avec ses quatre frères, Floyd, John Dory, Spruce et Clay, ils formaient le Boys Band le plus en vogue du moment, les BroZone. Alors qu’il n’était qu’un enfant, le groupe s’est séparé, tout comme la famille et depuis Branch n’a jamais revu ses frères. Mais quand Floyd, l’ainé de la fratrie est enlevé par les pires crapules des stars de la Pop, Velvet et Veneer, qui en veulent à son talent musical, Branch et Poppy vont se lancer dans une 8 poignante et bouleversante afin de réunir les frères ennemis et sauver Floyd d’un sort encore plus funeste que celui de vivre dans les oubliettes de la Pop Culture.", "Walt Dohrn",	12, "les_trolls3.jpg",	"https://www.youtube.com/watch?v=XLDfutXljfI",	0),
("Men in Black",	1997,	98,	"Deux agents secrets surveillent les extraterrestres vivant sur Terre.",	"Barry Sonnenfeld",	4,	"men_in_black1.jpg",	"https://www.youtube.com/watch?v=ubl2iqQO90E",	10),
("Men in Black II",	2002,	88,	"L’agent J doit retrouver K pour sauver la Terre d’une menace extraterrestre.",	"Barry Sonnenfeld",	4,	"men_in_black2.jpg",	"https://www.youtube.com/watch?v=HuQmpzpAhHo",	10),
("Men in Black III",	2012,	106,	"L’agent J voyage dans le passé pour sauver son partenaire et l’humanité.",	"Barry Sonnenfeld",	4, "men_in_black3.jpg",	"https://www.youtube.com/watch?v=Ep6NGpX66oU",	10),
("Metropolis",	1927,	153,	"Des ouvriers travaillent dans les souterrains d’une fabuleuse métropole de l’an 2026. Ils assurent le bonheur des nantis qui vivent dans les jardins suspendus de la ville. Un androïde mène les ouvriers vers la révolte.",	"Fritz Lang",	4,	"metropolis.jpg",	"https://www.youtube.com/watch?v=FFUGtw7uzB4",	0),
("One Piece Film Red", 	2020,	115,	"Luffy et son équipage s’apprêtent à assister à un festival de musique attendu avec impatience. La chanteuse la plus populaire du monde, Uta, va monter sur scène pour la première fois. Celle qui n’est autre que la fille du légendaire pirate Shanks Le Roux va révéler la puissance exceptionnelle de sa voix qui pourrait bien changer le monde…", "Goro Taniguchi",	5,	"one_piece_red.jpg",	"https://www.youtube.com/watch?v=H44eTKam6Uc",	0),
("Oppenheimer",	2023,	180,	"Le film retrace la vie de J. Robert Oppenheimer, physicien brillant mais tourmenté, depuis ses années de formation en Europe jusqu’à la direction du Projet Manhattan durant la Seconde Guerre mondiale. Chargé de concevoir la première bombe atomique, il rassemble une équipe de scientifiques à Los Alamos et mène l’essai Trinity, qui marque un tournant 11. Après les bombardements d’Hiroshima et de Nagasaki, Oppenheimer est rongé par la culpabilité et s’oppose au développement de l’arme thermonucléaire, ce qui le met en conflit avec certains de ses anciens collègues. Dans le climat tendu de la guerre froide, ses liens passés avec des communistes sont exploités contre lui, menant à la révocation de son habilitation de sécurité en 1954. Le récit alterne entre son ascension scientifique, ses dilemmes moraux et les conséquences politiques qui finiront par briser sa carrière, tout en posant la question du prix humain et éthique du progrès scientifique.",	"Christopher Nolan",	6,	"oppenheimer.webp",	"https://www.youtube.com/watch?v=CoXtvSRpHgM", 16),
("Pirates des Caraïbes",	2003,	143,	"Un pirate excentrique s’allie à un forgeron pour sauver une jeune femme.",	"Gore Verbinski",	8,	"pirate_des_caraibes.jpg",	"https://www.youtube.com/embed/WiZC7l0ovvk?si=kckHWMCeVow2KTBA",	10),
("Prince of Persia: The Sands of Time",	2010,	116,	"Un prince protège une dague magique capable de manipuler le temps.",	"Mike Newell",	8,	"prince_of_persia_the_sands_of_time.jpg",	"https://www.youtube.com/embed/mRDE5l-PJYY?si=seySexEKLXqRh47I",	10),
("Ring",	1998,	96,	"Tokyo, fin des années 2000, une ru­meur se répand parmi les adoles­cents : visionner une mystérieuse cassette vidéo provoquerait une mort cer­taine au bout d’une semaine. Après le dé­cès inexplicable de sa nièce, la journaliste Reiko Asakawa décide de mener l’enquête mais se retrouve elle-même sous le coup de la malédiction. Pendant les sept jours qui lui restent à vivre, elle devra remonter à l’origine de la vidéo fatale et affronter le spectre qui hante les télévisions : Sadako.",	"Hiroshi Takahashi",	7,	"ring.jpg",	"https://www.youtube.com/embed/mRDE5l-PJYY?si=seySexEKLXqRh47I",	12),
("Robots",	2005,	91,	"Un robot inventeur tente de changer le monde dans une société mécanique.",	"Chris Wedge",	5,	"robots.jpg",	"https://www.youtube.com/embed/zyLI71Z0RF4?si=ho-Z_7n8rWeUCp3q",	0),
("Rush Hour",	1998,	98,	"Un policier américain et un inspecteur chinois doivent collaborer pour sauver une enfant kidnappée.",	"Brett Ratner",	1,	"rush_our1.jpg",	"https://www.youtube.com/embed/JMiFsFQcFLE?si=rvrLiaPAu_qxTSoJ",	12),
("Rush Hour II",	2001,	90,	"Le duo enquête sur un réseau de fausse monnaie à Hong Kong.",	"Brett Ratner",	1,	"rush_our2.jpg",	"https://www.youtube.com/embed/SCTzYY95Aw4?si=fHMfExpl1CUEXCEc",	12),
("Sausage Party",	2016,	89,	"Une saucisse nommée Frank s'embarque dans une 8 périlleuse pour découvrir la vérité sur son existence. Accompagné de ses amis, il va tenter d'échapper à leur funeste destin après avoir découvert ce qui arrive réellement aux aliments lorsqu'ils sont choisis pour quitter le supermarché. Face aux dangers du monde extérieur et à la cruauté des humains, ils vont devoir s'unir pour mener une grande révolte et tenter de sauver leur peau.",	"Conrad Vernon",	5,	"sausage_party.jpg",	"https://www.youtube.com/embed/h_1d3q3mZ0o",	12),
("Scary Movie 1",	2000,	88,	"Un soir, Drew Becker recoit un appel anonyme d’un maniaque. Traquée dans sa maison, puis dans son jardin, elle finit par se faire tuer. Sa mort plonge ses camarades de lycée en plein cauchemar, d’autant qu’ils doivent désormais faire face à un tueur en série, caché parmi eux. Flairant le scoop, la journaliste Gail Hailstorn débarque en ville, bien décidée à harceler Cindy Campbell et ses amis à propos de cette histoire...",	"Shawn Wayans, Marlon Wayans",	2,	"scary_movie1.jpg",	"https://www.youtube.com/embed/SzpGYrrcJZw?si=Y5bPYvzQ1d8f6wq5",	16),
("Scary Movie 2",	2001,	83,	"Une année s’est écoulée depuis les meurtres désopilants qui se sont produits dans la paisible ville de Cindy Campbell. Et le tueur court toujours. Un jour, un professeur fou oblige Cindy et sa bande de copains déjantés à aller visiter une maison hantée pour une expérience scientifique. Ces derniers sont séduits par la perspective d’un week-end plein de frissons loin de l’université. Mais une fois pénétrés dans le manoir de l’enfer, les joyeux drilles découvrent qu’il existe des choses bien plus troublantes que ce qu’ils ont pu voir dans les vieux films d’7. Survivront-ils à la peur de leur vie ?",	"Shawn Wayans, Marlon Wayans",	2,	"scary_movie2.jpg",	"https://www.youtube.com/embed/zCFZUZxBVuI?si=EMsRcZ_OeY1EWyDy",	16),
("Scary Movie 3",	2003,	85,	"Pour Cindy, jeune et jolie reporter, le compte à rebours a déjà commencé. Parce qu’elle a visionné la cassette au pouvoir démoniaque, elle sait qu’il ne lui reste plus que sept jours à vivre. Si elle ne veut pas finir comme sa copine Brenda, elle doit absolument découvrir le secret de cette effroyable prophétie. Mais l’énigme est loin d’être simple et Cindy doit faire face à d’autres mystérieux phénomènes. Pourquoi les extraterrestres ont-ils laissé un étrange message géant dans le champ de Tom ? Pourquoi le Président des Etats-Unis est-il en train de virer barge ? Face aux épreuves, face aux stupéfiantes découvertes qui l’attendent, Cindy va devoir faire preuve de courage et résister au délire ambiant.",	"Pat Proft, Craig Mazin",	2,	"scary_movie3.jpg",	"https://www.youtube.com/embed/O21wD8Tzr2k?si=jQpU8uTda80G3-Te",	16),
("Scary Movie 4",	2006,	83,	"Cindy Campbell est toujours terriblement blonde. Mais bourrée de bonnes intentions. Ça tombe bien, elle vient d’être engagée comme aide à domicile auprès d’une vieille grabataire qui, grâce à ses soins vigilants, risque d’être enlevée à l’affection des siens beaucoup plus vite que prévu. Pendant que le spectre d’un gamin nu comme une poêle à frire fait de son mieux pour l’épouvanter à renfort de gribouillis sanguinolents, Cindy découvre que le voisin de sa protégée est du genre liant malgré l’irruption constante de deux petits êtres qui se prétendent ses enfants. Sur ce, des tripodes géants débarquent, deux campeurs sous une tente entonnent un slow de Lionel Richie, des gens ont des problèmes de cervicales, des individus en toge rouge customisée font fuir des villageois, bref c’est la gabegie...",	"Craig Mazin, Pat Proft",	2,	"scary_movie4.jpg",	"https://www.youtube.com/embed/-Bwr6LB5Dqw?si=CsMrhDiOITKsnYdy",	16),
("Scary Movie 5",	2013,	89,	"Jody et Dan, qui forment un jeune couple, emménagent avec leur bébé dans une maison où semblent se manifester d’étranges phénomènes. Ils vont faire appel à un médium... et au ballet pour faire la lumière sur cette malédiction.",	"John Aboud, Michael Colton",	2,	"scary_movie5.jpg",	"https://www.youtube.com/embed/RMDZ8M47j0I?si=s8Xupn5nMwQr08Vj",	16),
("Scooby !",	2020,	94,	'Dans SCOOBY!, on découvre comment Scooby et Sammy, amis pour la vie, se sont rencontrés et associés aux détectives en herbe Fred, Velma et Daphné pour créer la célèbre équipe Mystère et Cie. Après avoir résolu des centaines d’affaires et vécu d’innombrables 8s, Scooby et sa bande doivent désormais s’attaquer à leur énigme la plus redoutable : un complot destiné à déchaîner les forces du chien-fantôme Cerberus. Tandis qu’ils mettent tout en œuvre pour enrayer cette "acabocalypse" mondiale, nos amis découvrent que Scooby est porteur d’une lourde hérédité et qu’il est promis à un plus grand destin que quiconque aurait pu l’imaginer.',	"Tony Cervone",	2,	"scooby!.jpg",	"https://www.youtube.com/watch?v=1TEaxhn79Jc",	0),
("Sonic 1, le film",	2020,	99, "L’histoire du hérisson bleu le plus rapide du monde qui arrive sur Terre, sa nouvelle maison. Sonic et son nouveau meilleur ami Tom font équipe pour sauver la planète du diabolique Dr. Robotnik, bien déterminé à régner sur le monde entier.",	"Jeff Fowler",	8,	"sonic_le_film1.jpg",	"https://www.youtube.com/embed/szby7ZHLnkA?si=H1AHTqHHQvM97Yo_",	0),
("Sonic 2, le film",	2022,	122,	"Bien installé dans la petite ville de Green Hills, Sonic veut maintenant prouver qu’il a l’étoffe d’ un véritable héros. Un défi de taille se présente à lui quand le Dr Robotnik refait son apparition. Accompagné de son nouveau complice Knuckles, ils sont en quête d’une émeraude dont le pouvoir permettrait de détruire l’humanité toute entière. Pour s’assurer que l’émeraude ne tombe entre de mauvaises mains, Sonic fait équipe avec Tails. Commence alors un voyage à travers le monde, plein de péripéties.",	"Jeff Fowler",	8,	"sonic_le_film2.jpg",	"https://www.youtube.com/embed/G5kzUpWAusI?si=mCmGW5k7YT2XYVDI",	0),
("Sonic 3, le film",	2024,	109,	"Sonic, Knuckles et Tails se retrouvent face à un nouvel adversaire, Shadow, mystérieux et puissant ennemi aux pouvoirs inédits. Dépassée sur tous les plans, la Team Sonic va devoir former une alliance improbable pour tenter d’arrêter Shadow et protéger notre planète.",	"Jeff Fowler",	8,	"sonic_le_film3.jpg",	"https://www.youtube.com/embed/qSu6i2iFMO0?si=-hcAWWSTQLedm69Z",	0),
("Spider-Man: Across the Spider-Verse",	2023,	141,	"Après avoir retrouvé Gwen Stacy, Spider-Man, le sympathique héros originaire de Brooklyn, est catapulté à travers le Multivers, où il rencontre une équipe de Spider-Héros chargée d’en protéger l'existence. Mais lorsque les héros s'opposent sur la façon de gérer une nouvelle menace, Miles se retrouve confronté à eux et doit redéfinir ce que signifie être un héros afin de sauver les personnes qu'il aime le plus.",	"Phil Lord, Christopher Miller",	5,	"spiderman_across_the_spiderverse.jpg",	"https://www.youtube.com/embed/cqGjhVJWtEg?si=8Se4TUReWG6e--F0",	0),
("Spider-Man: Into the Spider-Verse",	2018,	117,	"Spider-Man : Into the Spider-Verse suit les 8s de Miles Morales, un adolescent afro-américain et portoricain qui vit à Brooklyn et s’efforce de s’intégrer dans son nouveau collège à Manhattan. Mais la vie de Miles se complique quand il se fait mordre par une araignée radioactive et se découvre des super-pouvoirs : il est désormais capable d’empoisonner ses adversaires, de se camoufler, de coller littéralement aux murs et aux plafonds ; son ouïe est démultipliée... Dans le même temps, le plus redoutable cerveau criminel de la ville, le Caïd, a mis au point un accélérateur de particules nucléaires capable d’ouvrir un portail sur d’autres univers. Son invention va provoquer l’arrivée de plusieurs autres versions de Spider-Man dans le monde de Miles, dont un Peter Parker plus âgé, Spider-Gwen, Spider-Man Noir, Spider-Cochon et Peni Parker, venue d’un dessin animé japonais.",	"Phil Lord, Rodney Rothman",	5,	"spiderman_into_the_spiderverse.png",	"https://www.youtube.com/embed/cqGjhVJWtEg?si=8Se4TUReWG6e--F0",	0),
("Star Wars, épisode I : La Menace fantôme", 	1999,	136,	"Avant de devenir un célèbre chevalier Jedi, et bien avant de se révéler l'âme la plus noire de la galaxie, Anakin Skywalker est un jeune esclave sur la planète Tatooine. La Force est déjà puissante en lui et il est un remarquable pilote de Podracer. Le maître Jedi Qui-Gon Jinn le découvre et entrevoit alors son immense potentiel. Pendant ce temps, l'armée de droïdes de l'insatiable Fédération du Commerce a envahi Naboo dans le cadre d'un plan secret des Sith visant à accroître leur pouvoir.",	"George Lucas",	4,	"starwars1.jpg",	"https://www.youtube.com/embed/bD7bpG-zDJQ?si=W5B7P99yUqF1SWtJ",	0),
("Star Wars, épisode II : L'Attaque des clones", 	2002,	142,	"Depuis le blocus de la planète Naboo par la Fédération du commerce, la République, gouvernée par le Chancelier Palpatine, connaît une véritable crise. Un groupe de dissidents, mené par le sombre Jedi comte Dooku, manifeste son mécontentement envers le fonctionnement du régime. Le Sénat et la population intergalactique se montrent pour leur part inquiets face à l'émergence d'une telle menace. Certains sénateurs demandent à ce que la République soit dotée d'une solide armée pour empêcher que la situation ne se détériore davantage. Parallèlement, Padmé Amidala, devenue sénatrice, est menacée par les séparatistes et échappe de justesse à un attentat. Le Padawan Anakin Skywalker est chargé de sa protection. Son maître, Obi-Wan Kenobi, part enquêter sur cette tentative de meurtre et découvre la constitution d'une mystérieuse armée de clones...",	"George Lucas",	4,	"starwars2.jpg",	"https://www.youtube.com/watch?v=arGWLDOeoOw",	0),
("Star Wars, épisode III : La Revanche des Sith", 2005,	140,	"La Guerre des Clones fait rage. Une franche hostilité oppose désormais le Chancelier Palpatine au Conseil Jedi. Anakin Skywalker, jeune Chevalier Jedi pris entre deux feux, hésite sur la conduite à tenir. Séduit par la promesse d'un pouvoir sans précédent, tenté par le côté obscur de la Force, il prête allégeance au maléfique Darth Sidious et devient Dark Vador. Les Seigneurs Sith s'unissent alors pour préparer leur revanche, qui commence par l'extermination des Jedi. Seuls rescapés du massacre, Yoda et Obi Wan se lancent à la poursuite des Sith. La traque se conclut par un spectaculaire combat au sabre entre Anakin et Obi Wan, qui décidera du sort de la galaxie.",	"George Lucas",	4,	"starwars3.jpg",	"https://www.youtube.com/watch?v=t1qtvKYwTV0",	0),
("Star Wars, épisode IV : Un nouvel espoir", 1997,	121,	"Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l'Empire galactique et l'Alliance rebelle. Capturée par les troupes de choc de l'Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l'Etoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s'échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au coeur des montagnes désertiques de Tatooine...", 	"George Lucas",	4,	"starwars4.jpg",	"https://www.youtube.com/watch?v=PNyht4iTMX8",	0),
("Star Wars, épisode IX : L'Ascension de Skywalker",  2019,	141,	"La conclusion de la saga Skywalker. De nouvelles légendes vont naître dans cette bataille épique pour la liberté.", 	"J. J. Abrams",	4,	"starwars9.jpg",	"https://www.youtube.com/watch?v=pHgwf2eMFnA",	0),
("Star Wars, épisode V : L'Empire contre-attaque", 	1980,	124,	"Malgré la destruction de l'Etoile Noire, l'Empire maintient son emprise sur la galaxie, et poursuit sans relâche sa lutte contre l'Alliance rebelle. Basés sur la planète glacée de Hoth, les rebelles essuient un assaut des troupes impériales. Parvenus à s'échapper, la princesse Leia, Han Solo, Chewbacca et C-3P0 se dirigent vers Bespin, la cité des nuages gouvernée par Lando Calrissian, ancien compagnon de Han. Suivant les instructions d'Obi-Wan Kenobi, Luke Skywalker se rend quant à lui vers le système de Dagobah, planète marécageuse où il doit recevoir l'enseignement du dernier maître Jedi, Yoda. Apprenant l'arrestation de ses compagnons par les stormtroopers de Dark Vador après la trahison de Lando, Luke décide d'interrompre son entraînement pour porter secours à ses amis et affronter le sombre seigneur Sith...", 	"Irvin Kershner",	4,	"starwars5.jpg",	"https://www.youtube.com/watch?v=Z7B0vfamFTE",	0),
("Star Wars, épisode VI : Le Retour du Jedi", 	1983,	134,	"L'Empire galactique est plus puissant que jamais : la construction de la nouvelle arme, l'Etoile de la Mort, menace l'univers tout entier... Arrêté après la trahison de Lando Calrissian, Han Solo est remis à l'ignoble contrebandier Jabba Le Hutt par le chasseur de primes Boba Fett. Après l'échec d'une première tentative d'évasion menée par la princesse Leia, également arrêtée par Jabba, Luke Skywalker et Lando parviennent à libérer leurs amis.",	"Richard Marquand",	4,	"starwars6.jpg",	"https://www.youtube.com/watch?v=5QSEJx3R968",	0),
("Star Wars, épisode VII : Le Réveil de la Force", 	2015,	138,	'Dans une galaxie lointaine, très lointaine, un nouvel épisode de la saga "Star Wars", 30 ans après les événements du "Retour du Jedi".', 	"J. J. Abrams",	4,	"starwars7.jpg",	"https://www.youtube.com/watch?v=mH9Ygfs5avo",	0),
("Star Wars, épisode VIII : Les Derniers Jedi", 2017,	152,	"Les héros du Réveil de la force rejoignent les figures légendaires de la galaxie dans une 8 épique qui révèle des secrets ancestraux sur la Force et entraîne de surprenantes révélations sur le passé…",	"Rian Johnson",	4,	"starwars8.jpg",	"https://www.youtube.com/watch?v=wY708Ky2SG8",	0),
("Star Wars: Starfighter", 	2027, 0,	"", "Shawn Levy",	4,	"starwars_starfighter",	"https://www.youtube.com/watch?v=wTwiovkhdHA",	0),
("Super Mario Bros, le film",	2023,	92,	"Alors qu’ils tentent de réparer une canalisation souterraine, Mario et son frère Luigi, tous deux plombiers, se retrouvent plongés dans un nouvel univers féerique à travers un mystérieux conduit. Mais lorsque les deux frères sont séparés, Mario s’engage dans une 8 trépidante pour retrouver Luigi. Dans sa quête, il peut compter sur l’aide du champignon Toad, habitant du Royaume Champignon, et les conseils avisés, en matière de techniques de combat, de la Princesse Peach, guerrière déterminée à la tête du Royaume. C’est ainsi que Mario réussit à mobiliser ses propres forces pour aller au bout de sa mission.",	"Matthew Fogel",	5,	"super_mario_bros_le_film.jpg",	"https://www.youtube.com/embed/iwst-UZn3wM?si=pntF_OzGOCKgcapw",	0),
("Super Mario Galaxy, le film",	2026,	99,	"À peine installés au Royaume Champignon, un mystérieux appel à l’aide va pousser Mario et Luigi à reprendre du service et plonger dans les zones d’ombre du passé de la princesse Peach. Une mission qui va propulser nos héros et leur nouvelle constellation d’amis, très loin de chez eux, à travers un périple intergalactique, à la découverte de nouveaux mondes où se forgeront des alliances pour le moins inattendues.",	"Matthew Fogel",	5,	"super_mario_galaxy_le_film.jpg",	"https://www.youtube.com/watch?v=BHRN7Oufjw4",	0),
("The Dark Knight, Le Chevalier Noir", 	2008,	152,	"Batman entreprend de démanteler les dernières organisations criminelles de Gotham. Mais il se heurte bientôt à un nouveau génie du crime qui répand la terreur et le chaos dans la ville : le Joker...", "Christopher Nolan",	6,	"the_dark_knight-le_chevalier_noir.jpg",	"https://www.youtube.com/watch?v=XGqgxGBn7Qw",	0),
("The Grand Budapest Hotel",	2014,	100,	"Bien que décrépit et quasi désert, le Grand Budapest Hotel, perché sur une corniche des alpes hongroises, porte encore l’empreinte de sa gloire d’antan. De passage en ce lieu, un écrivain lie conversation avec son propriétaire solitaire, Zero Mustafa.",	"Wes Anderson",	2,	"the_grand_budapest_hotel.jpg",	"https://www.youtube.com/embed/G1jG8HUY4zI",	0),
("The Mask",	1994,	101,	"Un homme trouve un masque magique qui lui donne des pouvoirs délirants.",	"Chuck Russell",	2,	"the_mask.jpg",	"https://youtu.be/LZl69yk5lEY?si=hzOHz8I6FbI3Dqp8",	10),
("The Matrix",	1999,	136,	"Un hacker découvre que la réalité est une simulation contrôlée par des machines et rejoint une rébellion.",	"Lana Wachowski, Lilly Wachowski",	4,	"matrix1.jpg",	"https://www.youtube.com/embed/m8e-FF8MsqU?si=iPU77uTN7mgJbyos",	12),
("The Truman Show",	1998,	103,	"Un homme découvre que sa vie est filmée en permanence pour une émission télévisée.",	"Peter Weir",	4,	"the_trueman_show.jpg",	"https://www.youtube.com/embed/dlnmQbPGuls?si=f6uF2iGb7rcNgbet",	10),
("Titanic",	1997,	194,	'Southampton, 10 avril 1912. Le paquebot le plus grand et le plus moderne du monde, réputé pour son insubmersibilité, le "Titanic", appareille pour son premier voyage. Quatre jours plus tard, il heurte un iceberg. A son bord, un artiste pauvre et une grande bourgeoise tombent amoureux.',	"James Cameron",	3,	"titanic.jpg",	"https://www.youtube.com/embed/CHekzSiZjrY?si=TW7cGyQ78jHwp2km",	12),
("Top Gun",	1986,	110,	'Jeune as du pilotage et tête brûlée d’une école réservée à l’élite de l’aéronavale US "Top Gun", Pete Mitchell, dit "Maverick", tombe sous le charme d’une instructrice alors qu’il est en compétition pour le titre du meilleur pilote...',	"Jim Cash, Jack Epps Jr.",	1,	"top_gun.jpg",	"https://www.youtube.com/embed/xa_z57UatDY?si=pZuh4guhgxVrxRNA",	12),
("Top Gun: Maverick",	2022,	131,	'Après avoir été l’un des meilleurs pilotes de chasse de la Marine américaine pendant plus de trente ans, Pete “Maverick" Mitchell continue à repousser ses limites en tant que pilote d’essai. Il refuse de monter en grade, car cela l’obligerait à renoncer à voler. Il est chargé de former un détachement de jeunes diplômés de l’école Top Gun pour une mission spéciale qu’aucun pilote n’aurait jamais imaginée. Lors de cette mission, Maverick rencontre le lieutenant Bradley “Rooster” Bradshaw, le fils de son défunt ami, le navigateur Nick “Goose” Bradshaw. Face à un avenir incertain, hanté par ses fantômes, Maverick va devoir affronter ses pires cauchemars au cours d’une mission qui exigera les plus grands des sacrifices.', "Christopher McQuarrie, Ehren Kruger",	1,	"top_gun_maverick.jpg",	"https://www.youtube.com/embed/qSqVVswa420?si=cabyT0kamRmRbBjY",	0),
("Tous à l’Ouest : une 8 de Lucky Luke", 	2007,	85,	"New York, 1855. Lucky Luke escorte les Dalton pour un énième procès. Inévitablement, les quatre affreux s’évadent et pillent en règle les nombreuses banques de la future Grosse Pomme. La police à ses trousses, Joe Dalton planque le magot dans le chariot d’une caravane d'immigrants en partance pour la Californie. Bon gré mal gré, sous l'oeil attentif du cow-boy solitaire, les Dalton s'intègrent dans la caravane pour de nouvelles 8s désopilantes.", 	"Olivier Jean-Marie", 13,	"tous_a_louest.jpg",	"https://www.youtube.com/watch?v=KGNLdlUTUvU",	0),
("Tous en scène 1",	2016,	110,	"Buster Moon est un élégant koala qui dirige un grand théâtre, jadis illustre, mais aujourd’hui tombé en désuétude. Buster est un éternel optimiste, un peu bougon, qui aime son précieux théâtre au-delà de tout et serait prêt à tout pour le sauver. C’est alors qu’il trouve une chance en or pour redorer son blason tout en évitant la destruction de ses rêves et de toutes ses ambitions: une compétition mondiale de chant. Cinq candidats sont retenus pour ce défi: Une souris aussi séduisante que malhonnête, un jeune éléphant timide dévoré par le trac, une truie mère de famille débordée par ses 25 marcassins, un jeune gorille délinquant qui ne cherche qu’à échapper à sa famille, et une porc épic punk qui peine à se débarrasser de son petit ami à l’égo surdimensionné pour faire une carrière solo. Tout ce petit monde va venir chercher sur la scène de Buster l’opportunité qui pourra changer leur vie à jamais.",	"Garth Jennings",	12, "tous_en_scene1.jpg",	"https://www.youtube.com/watch?v=yT0xM06V7Ac",	0),
("Tous en scène 2",	2021,	110,	"Si Buster et sa troupe ont fait du Nouveau Théâtre Moon la salle de concert à la mode, il est temps de voir les choses en plus grand : monter un nouveau spectacle dans la prestigieuse salle du théâtre de la Crystal Tower à Redshore City. Flanqué de sa troupe — dont Rosita la mère de famille nombreuse constamment débordée, Ash la rockeuse porc-épique, Johnny le gorille romantique, Meena l’éléphante à la timidité maladive sans oublier l’incroyable Gunter, le cochon le plus extraverti de la profession — Buster va devoir trouver comment se frayer un chemin dans les bureaux inhospitaliers de la prestigieuse Crystal Entertainment Company et atteindre son directeur, le loup du show-biz : Jimmy Crystal, qui y règne en véritable nabab. Dans un effort désespéré pour attirer l’attention de Jimmy, Gunter lance soudainement un pari fou que Buster relève sur le champ : la promesse de faire participer au spectacle le roi du rock, le lion Clay Calloway. Le problème est que… Buster n’a jamais rencontré Clay… surtout depuis que ce dernier s’est retiré de la scène 10 ans plus tôt, après avoir perdu sa femme. Mais pire que tout notre koala préféré ne se rend pas compte qu’il fait cette promesse à un escroc à l’égo surdimensionné qui préférerait défenestrer quelqu’un plutôt qu’on lui mente. Tiraillé entre les rêves de spectacle dithyrambique de Gunter et les menaces quasi littérales de Jimmy Crystal, qui en profite pour remplacer le rôle principal tenu par Rosita par sa propre fille pourrie gâtée Porsha, Buster va se mettre à la recherche de l’idole du rock pour le persuader de revenir sur scène. Ce qui avait commencé comme une course au succès va finir par rappeler à tous que la musique est le remède ultime pour tous les cœurs, même les plus brisés.", "Garth Jennings", 12,	"tous_en_scene2.jpg",	"https://www.youtube.com/watch?v=jjcp-7SS1Dk",	0),
("Troie",	2004,	162,	"Dans la Grèce antique, l'enlèvement d'Hélène, reine de Sparte, par Paris, prince de Troie, est une insulte que le roi Ménélas ne peut supporter. L’honneur familial étant en jeu, Agamemnon, frère de Ménélas et puissant roi de Mycènes, réunit toutes les armées grecques afin de faire sortir Hélène de Troie. Mais en réalité, la sauvegarde de l’honneur familial n’est qu’un prétexte pris par Agamemnon pour cacher sa terrible avidité. Celui-ci cherche en fait à contrôler Troie et à agrandir son vaste empire. Aucune armée n’a jamais réussi à pénétrer dans la cité fortifiée, sur laquelle veillent le roi Priam et le prince Hector. L’issue de la guerre de Troie dépendra notamment d’un homme, Achille, connu comme le plus grand guerrier de son époque. Arrogant, rebelle, et réputé invicible, celui-ci n’a d’attache pour rien ni personne si ce n’est sa propre gloire…",	"Wolfgang Petersen", 11,	"troie.jpg",	"https://www.youtube.com/watch?v=IeZrKyyXYjY",	0),
("Uncharted",	2022,	116,	"Nathan Drake, voleur astucieux et intrépide, est recruté par le chasseur de trésors chevronné Victor « Sully » Sullivan pour retrouver la fortune de Ferdinand Magellan, disparue il y a 500 ans. Ce qui ressemble d’abord à un simple casse devient finalement une course effrénée autour du globe pour s’emparer du trésor avant l’impitoyable Moncada, qui est persuadé que sa famille est l’héritière légitime de cette fortune. Si Nathan et Sully réussissent à déchiffrer les indices et résoudre l’un des plus anciens mystères du monde, ils pourraient rafler la somme de 5 milliards de dollars et peut-être même retrouver le frère de Nathan, disparu depuis longtemps… mais encore faudrait-il qu’ils apprennent à travailler ensemble.", "Art Marcum",	8,	"uncharted.jpg",	"https://www.youtube.com/watch?v=mduvAjUGl4s",	0),
("WALL-E",	2008,	98,	"Wall E, un petit robot, est le dernier être sur Terre ! Il y a 700 ans, l’humanité a déserté notre planète en lui laissant le soin de nettoyer la Terre. Mais Wall E a développé un petit défaut technique : une forte personnalité ! Curieux et indiscret, il est surtout très seul. Sa vie va être bouleversée avec l’arrivée d’Eve, une petite robot. Wall E va tout mettre en œuvre pour la séduire.",	"Andrew Stanton",	4,	"walle.jpg",	"https://www.youtube.com/embed/CZ1CATNbXg0?si=XZxGp0ckvYLvjRci", 0);

-- --------------------------------------------------------

--
-- Structure de la table `Profile`
--

CREATE TABLE `Profile` (
  `id_profile` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `pseudo` varchar(255) NOT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `min_age` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `Profile` (`pseudo`, `avatar`, `min_age`) VALUES
("Petits", "", 0),
("Enfant", "", 10),
("Pré-ado", "", 12),
("Ado", "", 16),
("Adulte", "", 18);

-- --------------------------------------------------------

--
-- Structure de la table `Favorite`
--

CREATE TABLE `Favorite` (
  `id_favorite` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `id_profile` int(11),
  `id_movie` int(11),
  `date_added` datetime DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`id_profile`) REFERENCES `Profile`(`id_profile`),
  FOREIGN KEY (`id_movie`) REFERENCES `Movie`(`id_movie`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
